### PR TITLE
Fix/html escaping

### LINKED ISSUE #23: Inline scripts are not correctly processed
For example:

```md
**Proof:** If <script type="math/tex; ">g</script> is concave, then <script type="math/tex; ">g(x)\\leq g(\\mu)+(x-\\mu)\'\\eta(\\mu),</script>
where <script type="math/tex; ">\\eta(\\mu)</script> is an arbitrary element of the
subgradient of ..
```

is returned as:

```
<p><strong>Proof:</strong> If <script type="math/tex; ">g</script> is concave, then <script type="math/tex; ">g(x)\leq g(\mu)+(x-\mu)\&#39;\eta(\mu),</script>
where <script type="math/tex; ">\eta(\mu)</script> is an arbitrary element of the
subgradient of ..</p>
```

(`'` is escaped in the `script`).

`<script type="math/tex; ">g(x)\leq g(\mu)+(x-\mu)\&#39;\eta(\mu),</script>` tag is processed as 2 `tags` (https://github.com/GitbookIO/kramed/blob/master/lib/lex/inline.js#L108), and its content is escaped

### PR DESCRIPTION
**Pull request by AaronO**
@SamyPesse Test if this correctly fixes #23 for you.

### CODE REVIEW

File: lib/lex/inline.js [hunk 1]
```diff
@@ -104,7 +104,47 @@ InlineLexer.prototype.output = function(src) {
...
+        // Outer tag
+        out += cap[0].substring(cap[0].indexOf(cap[2])+cap[2].length);
+        // Advance parser
+        src = src.substring(cap[0].length);
+        continue;
+      }
+
+      // Found a link
+      if(cap[1] === 'a' && cap[2] && !this.inLink) {
+        console.log('Parsing =', cap[2], 'to', this.output(cap[2]));
```
Comment (SamyPesse) [inline lib/lex/inline.js]: You should remove this line

**Comment by SamyPesse** [comment]
Tests need to be adapted since install is failing for old node versions.

File: lib/lex/inline.js (hunk 1 above)
Comment (AaronO) [inline lib/lex/inline.js]: Yes, there's some other debug stuff in there too (stuff in comments rather than deleted, I wanted to make sure this worked for you before deleting that and merging).
